##
# Any secret values, like an API key or database password, or Azure connection string.
##

[default]

############
# Database #
############

# db_password = ""

[dev]

############
# Database #
############

# db_password = ""

[prod]

############
# Database #
############

# db_password = ""
