##
# My standard Dynaconf settings.toml file.
#
# I normally put this file in a directory like src/config/settings.toml, then update my config.py, adding
# root_path="config" to the Dynaconf instance.
##

[default]

env = "prod"
container_env = false
log_level = "INFO"

############
# Database #
############

# db_type = "sqlite"
# db_drivername = "sqlite+pysqlite"
# db_username = ""
# # Set in .secrets.toml
# db_password = ""
# db_host = ""
# db_port = ""
# db_database = ".data/medcab.sqlite"
# db_echo = false

[dev]

env = "dev"
log_level = "DEBUG"

############
# Database #
############

# db_type = "sqlite"
# db_drivername = "sqlite+pysqlite"
# db_username = ""
# # Set in .secrets.toml
# db_password = ""
# db_host = ""
# db_port = ""
# db_database = ".data/medcab-dev.sqlite"
# db_echo = true

[prod]

############
# Database #
############

# db_type = "sqlite"
# db_drivername = "sqlite+pysqlite"
# db_username = ""
# # Set in .secrets.toml
# db_password = ""
# db_host = ""
# db_port = ""
# db_database = ".data/medcab.sqlite"
# db_echo = false
